- name: Deploy to EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      cd UTS_CICD
      sudo git pull
      sudo docker stop ecommerce-app || true
      sudo docker rm ecommerce-app || true
      sudo docker build -t ecommerce-app .
      sudo docker run -d -p 80:5000 ecommerce-app
