name: Deploy Flask to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd UTS_CICD/frontend
            sudo git pull
            sudo docker stop ecommerce-app || true
            sudo docker rm ecommerce-app || true
            sudo docker build -t ecommerce-app .
            sudo docker run -d -p 80:5000 ecommerce-app
