name: Deploy Flask to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ecommerce-app/frontend
            git pull
            docker stop ecommerce-app || true
            docker rm ecommerce-app || true
            docker build -t ecommerce-app .
            docker run -d -p 80:5000 ecommerce-app
